"""
Data models for the In-Memory Todo Console Application.

This module contains the core data structures used throughout the application.
All models are designed for future database migration (Phase II).
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Literal

# Type alias for todo status
TodoStatus = Literal["pending", "completed"]


@dataclass
class TodoItem:
    """
    Represents a single todo task.

    Attributes:
        id: Unique identifier (auto-generated by TodoStore)
        title: Main task description (required, non-empty)
        description: Optional additional details about the task
        status: Completion status ("pending" or "completed")
        created_at: Timestamp when the todo was created (local time)

    Example:
        >>> todo = TodoItem(
        ...     id=1,
        ...     title="Buy groceries",
        ...     description="Milk, eggs, bread",
        ...     status="pending",
        ...     created_at=datetime.now()
        ... )
    """

    id: int
    title: str
    description: str | None
    status: TodoStatus
    created_at: datetime
